spring:
    config:
        import: optional:file:.env[.properties]
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}

cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
        region:
            static: ${AWS_REGION}

application:
    bucket:
        name: ${AWS_BUCKET_NAME}
